// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL (non-pooled) used by Prisma CLI for migrations — bypasses PgBouncer
    // which blocks DDL statements. Runtime queries use DATABASE_URL (pooled) via
    // the @prisma/adapter-pg driver adapter in lib/db.ts.
    url: process.env["DIRECT_URL"] as string,
  },
});
