// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Load .env.local first (Next.js convention), then .env as fallback
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
dotenv.config({ path: ".env" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // DIRECT_URL (non-pooled) used by Prisma CLI for migrations — bypasses PgBouncer
    // which blocks DDL statements. Runtime queries use DATABASE_URL (pooled) via
    // the @prisma/adapter-pg driver adapter in lib/db.ts.
    url: process.env["DIRECT_URL"] as string,
  },
});
