// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Load .env.local first (Next.js convention), then .env as fallback
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
dotenv.config({ path: ".env" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prefer DIRECT_URL (non-pooled) for migrations — bypasses PgBouncer.
    // Falls back to DATABASE_URL if DIRECT_URL is not set (e.g. Vercel build env).
    url: (process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"]) as string,
  },
});
