-- Add commission pricing fields to JobCard
ALTER TABLE "JobCard" ADD COLUMN "spAmountCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "JobCard" ADD COLUMN "markedUpAmountCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "JobCard" ADD COLUMN "spPayoutCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "JobCard" ADD COLUMN "tierDiscountPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "JobCard" ADD COLUMN "spCommissionPercent" DOUBLE PRECISION NOT NULL DEFAULT 5;
